services:
  - type: web
    name: milestone-app
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: milestone-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_APP
        value: app.py

databases:
  - name: milestone-db
    plan: free
    databaseName: milestone_db
    user: milestone_admin